[2021-11-15T16:31:45.974786+01:00] php.DEBUG: Warning: filemtime(): stat failed for D:\xampp\htdocs\NRT_CleanIT\website-skeleton\config\routes\dev\web_profiler.yaml {"exception":{"Symfony\\Component\\ErrorHandler\\Exception\\SilencedErrorContext":{"severity":2,"file":"D:\\xampp\\htdocs\\NRT_CleanIT\\CleanIt\\vendor\\symfony\\config\\Resource\\FileResource.php","line":62,"trace":[{"file":"D:\\xampp\\htdocs\\NRT_CleanIT\\CleanIt\\vendor\\symfony\\config\\Resource\\SelfCheckingResourceChecker.php","line":34,"function":"isFresh","class":"Symfony\\Component\\Config\\Resource\\FileResource","type":"->"}],"count":1}}} []
[2021-11-15T16:31:47.615221+01:00] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET http://localhost/NRT_cleanit/CleanIt/public/" (from "http://localhost/NRT_cleanit/CleanIt/")" at D:\xampp\htdocs\NRT_CleanIT\CleanIt\vendor\symfony\http-kernel\EventListener\RouterListener.php line 136 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET http://localhost/NRT_cleanit/CleanIt/public/\" (from \"http://localhost/NRT_cleanit/CleanIt/\") at D:\\xampp\\htdocs\\NRT_CleanIT\\CleanIt\\vendor\\symfony\\http-kernel\\EventListener\\RouterListener.php:136)\n[previous exception] [object] (Symfony\\Component\\Routing\\Exception\\NoConfigurationException(code: 0):  at D:\\xampp\\htdocs\\NRT_CleanIT\\CleanIt\\vendor\\symfony\\routing\\Matcher\\Dumper\\CompiledUrlMatcherTrait.php:182)"} []
[2021-11-15T16:31:47.717942+01:00] app.ERROR: error while trying to collect executed migrations {"exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 1049): An exception occurred while executing a query: An exception occurred in the driver: SQLSTATE[HY000] [1049] Unknown database 'cleanit' at D:\\xampp\\htdocs\\NRT_CleanIT\\CleanIt\\vendor\\doctrine\\dbal\\src\\Driver\\API\\MySQL\\ExceptionConverter.php:98)\n[previous exception] [object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 1049): An exception occurred in the driver: SQLSTATE[HY000] [1049] Unknown database 'cleanit' at D:\\xampp\\htdocs\\NRT_CleanIT\\CleanIt\\vendor\\doctrine\\dbal\\src\\Driver\\API\\MySQL\\ExceptionConverter.php:98)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 1049): SQLSTATE[HY000] [1049] Unknown database 'cleanit' at D:\\xampp\\htdocs\\NRT_CleanIT\\CleanIt\\vendor\\doctrine\\dbal\\src\\Driver\\PDO\\Exception.php:26)\n[previous exception] [object] (PDOException(code: 1049): SQLSTATE[HY000] [1049] Unknown database 'cleanit' at D:\\xampp\\htdocs\\NRT_CleanIT\\CleanIt\\vendor\\doctrine\\dbal\\src\\Driver\\PDO\\Connection.php:34)"} []
